### ISSUE TITLE
Blank Prices should be `-` for `0` not blank spaces

### ISSUE THREAD

**Issue by luanmuniz** [jamesbrooks/poe-horticraft-pricing#1]
Hi,

I see in the screenshot that you are doing `#//2ex` or `#1ex//10c`

The correct semantics should be `#-/-/2ex` for `#0/0/2ex`.
The current format you are doing (`#//2ex`) will result in pricing the first craft in the station as `2ex`.

Just to point, I'm the creator of forbidden harvest.

By the way: THIS IS AWESOME!!!!

**Comment by jamesbrooks** [comment]
@luanmuniz Thanks for clearing that up! I think I did see the dash format but it must had evacuated my brain earlier on - I'll get that patched, cheers! :)

**Comment by jamesbrooks** [comment]
Fixed in 36619e4756aeb35a7c3cf8983e7f2ab71046103f
